language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - npm install seneca$SENECA_VER
  - psql -U postgres -f docker/dbschema.sql
